### ISSUE TITLE
android studio emulator 앱 실행 에러 해결

### ISSUE THREAD

**Issue by Hyuhak** [Dahagochi/Daha-gochi#1]
android emulator에서 앱이 실행이 안되는 에러는 새 플러터 프로젝트를 만들어서 실행하면 해결되는 것 같습니다.

pubspec.yaml파일에서 주석 처리된 부분을 지우고 asset을 추가했을 때 오류가 발생한 경험이 있는데, 이 에러도 비슷한 것 같습니다.

**Comment by Wisdom-Kim** [comment]
오류 원인을 알아보니 main branch에서는 MainActivity.kt가 없어서 생기는 문제였습니다!
말씀하신 것 처럼 프로젝트를 새로 만들어서 MainActivity.kt를 만들어도 되고, 따로 코틀린 파일을 생성하면 해결할 수 있었네요!
